services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $bundleConfig: '%huh_encore%'

  HeimrichHannot\EncoreBundle\Command\PrepareCommand:
    bind:
      Psr\Cache\CacheItemPoolInterface: '@webpack_encore.cache'