services:
  _defaults:
    public: true
    autowire: true

  huh.encore.listener.hooks:
    class: HeimrichHannot\EncoreBundle\EventListener\HookListener
  HeimrichHannot\EncoreBundle\EventListener\HookListener: '@huh.encore.listener.hooks'