services:
  _defaults:
    public: true
    autowire: true
    bind:
      $bundleConfig: '%huh_encore%'

  huh.encore.listener.hooks:
    class: HeimrichHannot\EncoreBundle\EventListener\HookListener
  HeimrichHannot\EncoreBundle\EventListener\HookListener: '@huh.encore.listener.hooks'

  HeimrichHannot\EncoreBundle\EventListener\GeneratePageListener: ~
  HeimrichHannot\EncoreBundle\EventListener\ReplaceDynamicScriptTagsListener: ~