services:
  _defaults:
    bind:
      $bundleConfig: '%huh_encore%'

  HeimrichHannot\EncoreBundle\Asset\PageEntrypoints:
    autowire: true

  HeimrichHannot\EncoreBundle\Asset\FrontendAsset:
    autowire: true
    public: true
  huh.encore.asset.frontend: '@HeimrichHannot\EncoreBundle\Asset\FrontendAsset'

  HeimrichHannot\EncoreBundle\Asset\EntrypointsJsonLookup:
    arguments:
      - "@service_container"
      - "@webpack_encore.cache"

  huh.encore.choice.entry:
    class: HeimrichHannot\EncoreBundle\Choice\EntryChoice
    public: true
    arguments:
      - "@contao.framework"
      - "@HeimrichHannot\\EncoreBundle\\Asset\\EntrypointsJsonLookup"
  huh.encore.choice.template.imports:
    class: HeimrichHannot\EncoreBundle\Choice\ImportsTemplateChoice
    public: true
    arguments:
      - "@contao.framework"
