services:
  _defaults:
    autowire: true
    bind:
      $bundleConfig: '%huh_encore%'
      $webDir: '%contao.web_dir%'

  HeimrichHannot\EncoreBundle\Asset\:
    resource: '../../Asset/*'
    exclude: '../../Asset/{EntrypointCollection.php,EntrypointsJsonLookup.php}'
    public: true

  huh.encore.asset.frontend:
    alias: HeimrichHannot\EncoreBundle\Asset\FrontendAsset
    public: true

  HeimrichHannot\EncoreBundle\Asset\EntrypointsJsonLookup:
    bind:
      Psr\Cache\CacheItemPoolInterface: "@webpack_encore.cache"

  huh.encore.asset.template:
    alias: HeimrichHannot\EncoreBundle\Asset\TemplateAsset
    public: true

  huh.encore.choice.entry:
    class: HeimrichHannot\EncoreBundle\Choice\EntryChoice
    public: true

  huh.encore.choice.template.imports:
    class: HeimrichHannot\EncoreBundle\Choice\ImportsTemplateChoice
    public: true

  HeimrichHannot\EncoreBundle\EventListener\Contao\:
    resource: "../../EventListener/Contao/*"
    public: true

  HeimrichHannot\EncoreBundle\:
    resource: "../../{DataContainer,Dca,Helper}/*"
    public: true