services:
  _defaults:
    autowire: true
    bind:
      $bundleConfig: '%huh_encore%'
      $webDir: '%contao.web_dir%'

  HeimrichHannot\EncoreBundle\:
    resource: "../../{DataContainer,Dca,EventListener,Helper,Migration}/*"
    public: true
    autoconfigure: true

  HeimrichHannot\EncoreBundle\Asset\:
    resource: '../../Asset/*'
    exclude: '../../Asset/{EntrypointCollection.php,EntrypointsJsonLookup.php}'
    public: true

  huh.encore.asset.frontend:
    alias: HeimrichHannot\EncoreBundle\Asset\FrontendAsset
    public: true

  HeimrichHannot\EncoreBundle\Asset\EntrypointsJsonLookup:
    bind:
      Psr\Cache\CacheItemPoolInterface: "@webpack_encore.cache"

  huh.encore.asset.template:
    alias: HeimrichHannot\EncoreBundle\Asset\TemplateAsset
    public: true

  huh.encore.choice.entry:
    class: HeimrichHannot\EncoreBundle\Choice\EntryChoice
    public: true

  huh.encore.choice.template.imports:
    class: HeimrichHannot\EncoreBundle\Choice\ImportsTemplateChoice
    public: true

  huh.encore.listener.hooks: '@HeimrichHannot\EncoreBundle\EventListener\HookListener'

#  huh.encore.listener.hooks:
#    class: HeimrichHannot\EncoreBundle\EventListener\HookListener
#  HeimrichHannot\EncoreBundle\EventListener\HookListener: '@huh.encore.listener.hooks'

#  HeimrichHannot\EncoreBundle\EventListener\GeneratePageListener: ~